AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Next.js deploy via AWS SAM demo

Globals:
  Function:
    Timeout: 10
  Api:
    OpenApiVersion: 3.0.2

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: nextjs-serverless-assets
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
  NextjsServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: next.out/code.zip
      MemorySize: 512
      Handler: server.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Layers:
        - !Ref NextjsServerLayer
      Events:
        Proxy:
          Type: Http
          Properties:
            Path: /_server/{proxy+}
            Method: ANY
      DeploymentPreference:
        Type: AllAtOnce
  NextjsServerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Next.js Server Dependencies
      ContentUri: next.out/dependenciesLayer.zip
  NextjsImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: node_modules/@sladg/imaginex-lambda/build/code.zip
      MemorySize: 512
      Handler: imaginex_lambda/handler.handler
      Runtime: python3.8
      Layers:
        - !Ref NextjsImageLayer
      Events:
        Proxy:
          Type: Http
          Properties:
            Path: /_image/{proxy+}
            Method: ANY
      DeploymentPreference:
        Type: AllAtOnce
      Policies:
        - S3ReadPolicy:
            BucketName: nextjs-serverless-assets
  NextjsImageLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Next.js Image Optimization Dependencies
      ContentUri: node_modules/@sladg/imaginex-lambda/build/dependencies-layer.zip
  NextjsCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: nextjs-serverless-assets.s3.amazonaws.com
            Id: myS3Origin
            S3OriginConfig:
              OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: https-only
        PriceClass: PriceClass_All
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
