version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo ${BUILD_ENV}
      - npm ci
  build:
    commands:
      - npm run build
      - npm run package
      - sam package --template-file template.yml --s3-bucket ${SAM_BUCKET} --output-template-file packaged-template.yml
cache:
  paths:
    - .next/cache/**/*
artifacts:
  files:
    - packaged-template.yml
    - pipeline/*
